version: '3'
services:
  tomcat:
    image: ubuntu:tomcat
    container_name: tomcat
    build: .
    ports:
      - "8888:8080"
    volumes:
      - ./web:/opt/apache-tomcat-8.0.53/webapps/ROOT
    links:
      - oracle
    restart: always
    environment:
      - TZ=Asia/Shanghai #设定时区
  oracle:
    image: wnameless/oracle-xe-11g-r2
    container_name: oracle
    ports:
      - "1521:1521"
      - "8080:8080"
    volumes:
      - ./src/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    working_dir: /u01/app/oracle
    restart: always
    environment:
      - TZ=Asia/Shanghai
