version: '3'
services:
  tomcat:
    image: tomcat:8.5-jdk8-corretto
    container_name: tomcat
    ports:
      - "83:8080"
    volumes:
      - ./src/ojdbc6.jar:/usr/local/tomcat/lib/ojdbc6.jar
      - ./web:/usr/local/tomcat/webapps/ROOT
    links:
      - oracle11g
    restart: always
    environment:
      - TZ=Asia/Shanghai #设定时区
  oracle:
    image: wnameless/oracle-xe-11g-r2
    container_name: oracle11g
    ports:
      - "1521:1521" #oracle 端口
      - "84:8080" #oracle 管理页面端口
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    working_dir: /u01/app/oracle
    restart: always
    environment:
      - TZ=Asia/Shanghai
