version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "84:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html/
    restart: "no"
    environment: #设置环境变量
      - TZ=Asia/Shanghai #设定时区
