version: '3'
services:
  apache:
    image: ubuntu:apache
    container_name: apache
    build: .
    ports:
      - "81:80"
    volumes:
      - ./web:/var/www/html
    links:
      - mysql
    environment:
      - TZ=Asia/Shanghai #设定时区
    restart: always
  mysql:
    image: mysql:5.5
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai